# src/main/resources/application.yml
server:
  port: ${PORT:8080}   # Use Render's PORT if present

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking}
    username: ${SPRING_DATASOURCE_USERNAME:booking}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret}
    expirationSeconds: 86400