spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/booking
#    username: masabwakny
#    password: Booking123
#    driver-class-name: org.postgresql.Driver
  url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking}
  username: ${SPRING_DATASOURCE_USERNAME:booking}
  password: ${SPRING_DATASOURCE_PASSWORD:password}
  driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080


#app:
#  jwt:
#    secret: ${JWT_SECRET:48f7e2f3d3a8e64d8bjnroe876ubn98h9h34ji4ce1c9a12a84}
#    expirationSeconds: 86400
app:
  jwt:
    secret: ${JWT_SECRET:dev-secret}
    expirationSeconds: 86400



#management:
#  endpoints:
#    web:w
#      exposure:
#        include: health,info
#  endpoint:
#    health:
#      show-details: always

management:
  endpoints:
    web.exposure.include: health,info
  endpoint:
    health.show-details: never